services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    security_opt:
      - no-new-privileges:true

volumes:
  db_volume:
